= History Of IEEE Compute

==== Know how we started...

The IEEE Compute Newsletter is the brainchild of the IEEE India Council CS SAC. Since its conception in 2015, when the first volume hit the stands for all the curious minds in India, the IEEE Compute Newsletter has been serving as a means to communicate the events, trends and developments in the computer industry to its readers. Two very successful issues of the Newsletter have been released with the inspiring hard work and commitment shown by the teams working for the Newsletter. These teams are unique in their diversity, with members from different streams, universities, and states, working together, untiringly, to bring the newsletter to its communicative potential.

Past newsletters contained brief accounts of the various activities and events organized by the different sections of IEEE, throughout India. Topics ranging from Quantum Computing to Security in Cloud Computing were covered in the past, in a comprehensible yet concise manner, making it easy for readers from all over the country to understand the concepts without over-complicating the subject matter. Aside from technological innovations, the newsletters also contained interviews with inspiring personalities for readers to derive motivation from, to excel in their endeavors.

Despite its past success, the Compute team knows that there is always more room for improvement. With new worker bees joining the growing beehive that is the Newsletter team, efforts are being made to come out with more captivating, engaging and ultimately stimulating articles for readers. Putting out relevant and stirring content has always been a priority for the Compute team and this issue of the IEEE Compute Newsletter aims to fulfill these goals and more.